### ISSUE TITLE
Transparency and Statistics

### ISSUE THREAD

**Issue by JesperDramsch** [softwareunderground/code-of-conduct#3]
I suggest a transparency report at set intervals. The report should be anonymized. Often it's good to have reports after events as [Pycon UK](https://2018.pyconuk.org/code-conduct/transparency-report/) does.

Additionally, it would be good to maintain completely anonymized statistics in this repository modelling the [Django Stats](https://github.com/django/code-of-conduct/blob/master/statistics.md).

Reports should be kept confidential but saved accessible only to members of the committee. A Google Spreadsheet lends itself to this format.

**Comment by leouieda** [comment]
I don't fully understand the motivation for this. Sure, having data is nice but is it worth the effort for our case? What kind of data are we talking about?

**Comment by JesperDramsch** [comment]
Mostly number of reports and action taken.

I believe just having a CoC is a toothless tiger. I think we should create a space where we can be inclusive and creating a clear process produces trust. 

We are increasingly moving into meatspace with transform etc. I think part of the transparency is signaling that we are thinking about inclusivity and diversity and that we are willing to put the work in.

The slack community has over 150 active members with over 1000 registered. I would just like to see this community grow into something that models the communities I've seen in the python spaces where people could join and feel welcome despite historically feeling excluded in our wider field. 

(And if there are no reports, which we would clearly hope for, the work is minimal, so nothing is lost.)

**Comment by leouieda** [comment]
:+1: that is a great point! I'm convinced :)
